accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('update/', views.update_view, name='update'),
    path('delete/', views.delete_view, name='delete'),
    path('contact/', views.contact, name='contact'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include
from scraping import views
from scraping.views import VacancyDetailView, VacancyListView, VacancyCreateView, VacancyUpdateView, VacancyDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    # path('list/', views.list_view, name='list'),
    # path('detail/<int:pk>/', views.v_detail, name='detail'),

    path('detail/<slug:id>/', VacancyDetailView.as_view(), name='detail'),
    path('list/', VacancyListView.as_view(), name='list'),
    path('create/', VacancyCreateView.as_view(), name='create'),
    path('update/<slug:id>/', VacancyUpdateView.as_view(), name='update'),
    path('delete/<slug:id>/', VacancyDeleteView.as_view(), name='delete'),

    path('accounts/', include('accounts.urls')),
    path('api/', include('scraping.api.urls')),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import UserManager
from django.db import models


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    city = models.ForeignKey('scraping.City', on_delete=models.SET_NULL,
                             null=True, blank=True)
    language = models.ForeignKey('scraping.Language', on_delete=models.SET_NULL,
                                 null=True, blank=True)
    send_email = models.BooleanField(default=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import check_password
from django.core.exceptions import ValidationError
from scraping.models import City, Language


User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter the email',
    }))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter the password',
    }))

    def clean(self, *args, **kwargs):
        '''
        qs[0] - to take first element
        .password = take the password of first element
        '''
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password').strip()
        if email and password:
            qs = User.objects.filter(email=email)
            if not qs.exists():
                raise ValidationError('There is no such user')
            if not check_password(password, qs[0].password):
                raise ValidationError("Invalid password")
            user = authenticate(email=email, password=password)
            if not user:
                raise ValidationError("The user's account is disabled")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(forms.ModelForm):
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter the email',
    }))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter the password',
    }))
    password2 = forms.CharField(label='Confirm', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Confirm the password',
    }))

    def clean_password2(self):
        data = self.cleaned_data
        if data['password1'] != data['password2']:
            raise ValidationError("Passwords did not match")
        return data['password2']

    class Meta:
        model = User
        fields = ('email', )


class UserUpdateForm(forms.Form):
    city = forms.ModelChoiceField(label='City', queryset=City.objects.all(),
                                  to_field_name='slug', required=True,
                                  widget=forms.Select(attrs={
                                      'class': 'form-control js-example-basic-single'}))
    language = forms.ModelChoiceField(label='Programming language', queryset=Language.objects.all(),
                                      to_field_name='slug', required=True,
                                      widget=forms.Select(attrs={
                                          'class': 'form-control js-example-basic-single'}))
    send_email = forms.BooleanField(required=False, widget=forms.CheckboxInput, label='Subscribe to the mailing?')

    class Meta:
        model = User
        fields = ('city', 'language', 'send_email', )


class ContactForm(forms.Form):
    city = forms.CharField(label='City',
                           required=True,
                           widget=forms.TextInput(attrs={
                               'class': 'form-control',
                               'placeholder': 'Enter the city',
                           }))
    language = forms.CharField(label='Programming language',
                               required=True,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Enter the programming language',
                               }))
    email = forms.CharField(label='Email', required=True,
                            widget=forms.EmailInput(attrs={
                                'class': 'form-control',
                                'placeholder': 'Enter the email',
                            }))

accounts/views.py
import datetime
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from .forms import UserLoginForm, UserRegistrationForm, UserUpdateForm, ContactForm
from django.contrib import messages
from scraping.models import Error

User = get_user_model()


def login_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        email = data.get('email')
        password = data.get('password')
        user = authenticate(request, email=email, password=password)
        login(request, user)
        return redirect('home')
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('home')


def register_view(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password1'])
        new_user.save()
        messages.success(request, 'The user has been added to the system')
        return render(request, 'accounts/register_done.html', {'new_user': new_user})
    return render(request, 'accounts/register.html', {'form': form})


def update_view(request):
    contact_form = ContactForm()
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            form = UserUpdateForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                user.city = data['city']
                user.language = data['language']
                user.send_email = data['send_email']
                user.save()
                messages.success(request, 'The information has been updated')
                return redirect('accounts:update')
        form = UserUpdateForm(initial={
            'city': user.city,
            'language': user.language,
            'send_email': user.send_email,
        })
        context = {
            'form': form,
            'contact_form': contact_form,
        }
        return render(request, 'accounts/update.html', context)
    else:
        return redirect('accounts:login')


def delete_view(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            qs = User.objects.get(pk=user.pk)
            qs.delete()
            messages.error(request, 'The user was deleted')
    return redirect('home')


def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST or None)
        if contact_form.is_valid():
            data = contact_form.cleaned_data
            city = data.get('city')
            language = data.get('language')
            email = data.get('email')
            qs = Error.objects.filter(timestamp=datetime.date.today())
            if qs.exists():
                err = qs.first()
                data = err.data.get('user_data', [])
                data.append({'city': city, 'language': language, 'email': email})
                err.data['user_data'] = data
                err.save()
            else:
                data = {'user_data': [
                    {'city': city, 'language': language, 'email': email}
                ]}
                Error(data=data).save()
            messages.success(request, 'Your application has been successfully submitted')
            return redirect('accounts:update')
        else:
            return redirect('accounts:update')
    else:
        return redirect('accounts:login')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6 mx-auto">
        <h4 align="center">Login form</h4>
        <form method="POST" action="">{% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Log in</button><br><br>
        </form>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6 mx-auto">
        <h4 align="center">Registering a new user</h4>
        <form method="POST" action="">{% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Sign up</button><br><br>
        </form>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% block title %}
Successful registration
{% endblock %}

{% block content %}
<br>

<div class="row">
    <div class="col-md-6 mx-auto">
        <h2 align="center">Hello, {{ new_user.email }}.<br>You have successfully created an account</h2>
        <h4 align="center">
            Now you can <a href="{% url 'accounts:login' %}">log in</a>
        </h4>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %}
User Settings
{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6 mx-auto">
        <h4 align="center">User Settings</h4>
        <form method="POST" action="">{% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <div class="box-parent">
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <form method="POST" action="{% url 'accounts:delete' %}">{% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete User</button>
        </form>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-6 mx-auto"><br><br>
        <h4 align="center">Use this form to request the ability to search by the specified parameters</h4>
        <center><p>
          <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Show Form
          </button>
        </p></center>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
              <form method="POST" action="{% url 'accounts:contact' %}">{% csrf_token %}
                <div class="form-group">
                    {{ contact_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
              </form>
          </div>
        </div>
    </div>
</div>

{% endblock %}