accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('update/', views.update_view, name='update'),
    path('delete/', views.delete_view, name='delete'),
    path('contact/', views.contact, name='contact'),
]

scraping_service/urls.py
from django.contrib import admin
from django.urls import path, include
from scraping import views
from scraping.views import VacancyDetailView, VacancyListView, VacancyCreateView, VacancyUpdateView, VacancyDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    # path('list/', views.list_view, name='list'),
    # path('detail/<int:pk>/', views.v_detail, name='detail'),

    path('detail/<slug:id>/', VacancyDetailView.as_view(), name='detail'),
    path('list/', VacancyListView.as_view(), name='list'),
    path('create/', VacancyCreateView.as_view(), name='create'),
    path('update/<slug:id>/', VacancyUpdateView.as_view(), name='update'),
    path('delete/<slug:id>/', VacancyDeleteView.as_view(), name='delete'),

    path('accounts/', include('accounts.urls')),
    path('api/', include('scraping.api.urls')),
]

templates/base.html
{% load static %}

{% url 'accounts:update' as update_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:login' as login_url %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'accounts/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="icon" href='{% static "favicon.ico" %}'>
    <title>{% block title %}Job Finder{% endblock %}</title>
  </head>
  <body>


  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f1f1f0;">
    <a class="navbar-brand" href="{% url 'home' %}" id="brand">Job Finder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == update_url %} active {% endif %}" href="{% url 'accounts:update' %}">User settings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == login_url %} active {% endif %}" href="{% url 'accounts:login' %}">Sign in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == register_url %} active {% endif %}" href="{% url 'accounts:register' %}">Sign up</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  </div>


  <div class="container">
     <div class="row">
        <div class="col-md-8 mx-auto">
          {% if messages %}
                {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                {% endfor %}
          {% endif %}
        </div>
     </div>
  </div>


  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  <script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });
  </script>
  </body>
</html>